In [ ]:
!pip install ipywidgets

In [52]:
import numpy as np
import pandas as pd
import ipywidgets as widgets
from IPython.display import display
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection  import train_test_split

In [53]:
aj=pd.read_csv(r"D:\30 Cource\CreditRisk.csv")
aj.head(5)

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [54]:
aj.drop(['Loan_ID'],axis=1)

Gender Married  Dependents     Education Self_Employed  ApplicantIncome  \
0     Male      No         0.0      Graduate            No             5849   
1     Male     Yes         1.0      Graduate            No             4583   
2     Male     Yes         0.0      Graduate           Yes             3000   
3     Male     Yes         0.0  Not Graduate            No             2583   
4     Male      No         0.0      Graduate            No             6000   
..     ...     ...         ...           ...           ...              ...   
976   Male     Yes         4.0  Not Graduate           Yes             4009   
977   Male     Yes         0.0      Graduate            No             4158   
978   Male      No         0.0      Graduate            No             3250   
979   Male     Yes         0.0      Graduate            No             5000   
980   Male      No         0.0      Graduate           Yes             9200   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
976             1777.0       113.0             360.0             1.0   
977              709.0       115.0             360.0             1.0   
978             1993.0       126.0             360.0             NaN   
979             2393.0       158.0             360.0             1.0   
980                0.0        98.0             180.0             1.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
976         Urban           Y  
977         Urban           Y  
978     Semiurban           Y  
979         Rural           N  
980         Rural           Y  

[981 rows x 12 columns]

In [55]:
aj.isnull().sum()

Loan_ID               0
Gender               24
Married               3
Dependents           25
Education             0
Self_Employed        55
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           27
Loan_Amount_Term     20
Credit_History       79
Property_Area         0
Loan_Status           0
dtype: int64

In [56]:
#Null Values
aj.Gender=aj.Gender.fillna("Male")
aj.Married=aj.Married.fillna("Yes")
aj.Dependents=aj.Dependents.fillna(1.0)
aj.Self_Employed=aj.Self_Employed.fillna("No")
aj.LoanAmount=aj.LoanAmount.fillna(aj.LoanAmount.mean())
aj.Loan_Amount_Term=aj.Loan_Amount_Term.fillna(aj.Loan_Amount_Term.mean())
aj.Credit_History=aj.Credit_History.fillna(0)

#Text to numrical
aj.Gender=aj.Gender.replace({'Male':0,'Female':1})
aj.Married=aj.Married.replace({'No':0,'Yes':1})
aj.Education=aj.Education.replace({"Graduate":0,"Not Graduate":1})
aj.Self_Employed=aj.Self_Employed.replace({"No":0,"Yes":1})
aj.Property_Area=aj.Property_Area.replace({"Urban":0,"Semiurban":1,"Rural":2})
aj.Loan_Status=aj.Loan_Status.replace({"Y":1,"N":0})



aj=aj.drop(['Loan_ID'],axis=1)

In [57]:
aj.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [58]:
aj

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         0        0         0.0          0              0             5849   
1         0        1         1.0          0              0             4583   
2         0        1         0.0          0              1             3000   
3         0        1         0.0          1              0             2583   
4         0        0         0.0          0              0             6000   
..      ...      ...         ...        ...            ...              ...   
976       0        1         4.0          1              1             4009   
977       0        1         0.0          0              0             4158   
978       0        0         0.0          0              0             3250   
979       0        1         0.0          0              0             5000   
980       0        0         0.0          0              1             9200   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0   142.51153             360.0             1.0   
1               1508.0   128.00000             360.0             1.0   
2                  0.0    66.00000             360.0             1.0   
3               2358.0   120.00000             360.0             1.0   
4                  0.0   141.00000             360.0             1.0   
..                 ...         ...               ...             ...   
976             1777.0   113.00000             360.0             1.0   
977              709.0   115.00000             360.0             1.0   
978             1993.0   126.00000             360.0             0.0   
979             2393.0   158.00000             360.0             1.0   
980                0.0    98.00000             180.0             1.0   

     Property_Area  Loan_Status  
0                0            1  
1                2            0  
2                0            1  
3                0            1  
4                0            1  
..             ...          ...  
976              0            1  
977              0            1  
978              1            1  
979              2            0  
980              2            1  

[981 rows x 12 columns]

In [59]:
train_aj,test_aj=train_test_split(aj,train_size=0.8,test_size=0.2)
train_aj.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
934       0        1         1.0          0              0             2667   
118       0        1         0.0          0              0             5568   
4         0        0         0.0          0              0             6000   
668       0        1         0.0          1              1             5293   
24        0        1         1.0          0              0             3717   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
934             1542.0       148.0             360.0             1.0   
118             2142.0       175.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
668                0.0        92.0             360.0             1.0   
24              2925.0       151.0             360.0             0.0   

     Property_Area  Loan_Status  
934              2            1  
118              2            0  
4                0            1  
668              0            1  
24               1            0

In [60]:
x_train=train_aj.iloc[:,0:-1]
y_train=train_aj.iloc[:,-1]

x_test=test_aj.iloc[:,0:-1]
y_test=test_aj.iloc[:,-1]

#1. Scikit-learn Models

In [61]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, accuracy_score, classification_report, confusion_matrix


In [62]:
###                           Linear Regression                           ###

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
predictions = model.predict(x_test)
predictions

array([0.93294645, 0.82207348, 0.30229441, 0.84343672, 0.22915041,
       0.23850797, 0.26455468, 0.81260441, 0.80796539, 0.8704872 ,
       0.88468048, 0.76244681, 0.87528214, 0.87743225, 0.98247341,
       0.9849289 , 0.79983847, 0.78282393, 0.81349823, 0.29758276,
       0.36572154, 0.78608774, 0.83156154, 0.90490746, 0.23464471,
       0.46201183, 0.41939297, 0.36345988, 0.82854994, 0.8829177 ,
       0.91423533, 0.83336895, 0.85218122, 0.92433158, 0.93860394,
       0.86822674, 0.93449358, 0.88080138, 0.20486926, 0.24395741,
       0.77397642, 0.20727961, 0.80858735, 0.34503486, 0.90997545,
       0.26467001, 0.91520364, 0.92210817, 0.87136945, 0.84413426,
       0.75798891, 0.8888974 , 0.86145764, 0.35120485, 0.83468987,
       0.84725802, 0.30667807, 0.96636913, 0.30143137, 0.86656985,
       0.28257018, 0.97270717, 1.03056757, 0.93263992, 0.25009684,
       0.44205196, 0.75486959, 0.92559129, 0.80611647, 0.43714177,
       0.8601352 , 0.36710132, 0.82813992, 0.68410796, 0.84306

In [63]:
# Calculate evaluation metrics
r2 = r2_score(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)

print(f'R² Score: {r2}')
print(f'Mean Absolute Error (MAE): {mae}')
print(f'Mean Squared Error (MSE): {mse}')
print(f'Root Mean Squared Error (RMSE): {rmse}')

R² Score: 0.2639271882513905
Mean Absolute Error (MAE): 0.291880689042316
Mean Squared Error (MSE): 0.14645969368761794
Root Mean Squared Error (RMSE): 0.38270052742009375


In [64]:
###                             Decision Tree                             ###

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train, y_train)
predictions = model.predict(x_test)
predictions

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
      dtype=int64)

In [65]:
# Calculate evaluation metrics
accuracy = accuracy_score(y_test, predictions)
report = classification_report(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions)

# Print results
print(f'Accuracy Score: {accuracy}')
print('Classification Report:\n', report)
print('Confusion Matrix:\n', conf_matrix)

Accuracy Score: 0.7106598984771574
Classification Report:
               precision    recall  f1-score   support

           0       0.47      0.46      0.47        54
           1       0.80      0.80      0.80       143

    accuracy                           0.71       197
   macro avg       0.64      0.63      0.63       197
weighted avg       0.71      0.71      0.71       197

Confusion Matrix:
 [[ 25  29]
 [ 28 115]]


In [66]:
###                         Random Forest                               ###

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train, y_train)
Ran_predictions = model.predict(x_train)
predictions

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
      dtype=int64)

In [67]:
# Predictions on the test set
Ran_predictions = model.predict(x_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, Ran_predictions)
report = classification_report(y_test, Ran_predictions)
conf_matrix = confusion_matrix(y_test, Ran_predictions)

# Print results
print(f'Accuracy Score: {accuracy}')
print('Classification Report:\n', report)
print('Confusion Matrix:\n', conf_matrix)

Accuracy Score: 0.7766497461928934
Classification Report:
               precision    recall  f1-score   support

           0       0.63      0.44      0.52        54
           1       0.81      0.90      0.85       143

    accuracy                           0.78       197
   macro avg       0.72      0.67      0.69       197
weighted avg       0.76      0.78      0.76       197

Confusion Matrix:
 [[ 24  30]
 [ 14 129]]


In [77]:
# Splitting dataset into train-test
train_aj, test_aj = train_test_split(aj, train_size=0.8, test_size=0.2, random_state=42)

In [78]:
# Define feature columns
feature_columns = [col for col in aj.columns if col not in ['Loan_Status', 'LoanAmount']]

In [79]:
# Features & target for classification
X_train = train_aj[feature_columns]
y_train = train_aj['Loan_Status']

X_test = test_aj[feature_columns]
y_test = test_aj['Loan_Status']

In [80]:
# Train Random Forest Classifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [81]:
# Classification Accuracy
y_pred = clf.predict(X_test)
print("Loan Approval Accuracy:", accuracy_score(y_test, y_pred))


Loan Approval Accuracy: 0.766497461928934


In [82]:
# Train Regression Models for Loan Amount Prediction
approved_loans = train_aj[train_aj['Loan_Status'] == 1]
rejected_loans = train_aj[train_aj['Loan_Status'] == 0]

reg_approved = RandomForestRegressor(random_state=42)
reg_rejected = RandomForestRegressor(random_state=42)

reg_approved.fit(approved_loans[feature_columns], approved_loans['LoanAmount'])
reg_rejected.fit(rejected_loans[feature_columns], rejected_loans['LoanAmount'])

RandomForestRegressor(random_state=42)

In [87]:
# Define interactive widgets
gender = widgets.Dropdown(options=[("Male", 0), ("Female", 1)], description="Gender:")
married = widgets.Dropdown(options=[("No", 0), ("Yes", 1)], description="Married:")
dependents = widgets.IntSlider(min=0, max=5, value=1, description="Dependents:")
education = widgets.Dropdown(options=[("Graduate", 0), ("Not Graduate", 1)], description="Education:")
self_employed = widgets.Dropdown(options=[("No", 0), ("Yes", 1)], description="Self-Employed:")
applicant_income = widgets.IntText(value=5000, description="Applicant Income:")
coapplicant_income = widgets.IntText(value=2000, description="Coapplicant Income:")
loan_term = widgets.IntSlider(min=12, max=480, value=360, step=12, description="Loan Term:")
credit_history = widgets.Dropdown(options=[("No", 0), ("Yes", 1)], description="Credit History:")
property_area = widgets.Dropdown(options=[("Urban", 0), ("Semiurban", 1), ("Rural", 2)], description="Property Area:")
requested_loan = widgets.IntText(value=100000, description="Requested Loan Amount:")
predict_button = widgets.Button(description="Check Eligibility")
# Function to predict loan status
def predict_loan_status(_):
    user_data = {
        "Gender": gender.value,
        "Married": married.value,
        "Dependents": dependents.value,
        "Education": education.value,
        "Self_Employed": self_employed.value,
        "ApplicantIncome": applicant_income.value,
        "CoapplicantIncome": coapplicant_income.value,
        "Loan_Amount_Term": loan_term.value,
        "Credit_History": credit_history.value,
        "Property_Area": property_area.value,
    }
    
    user_df = pd.DataFrame([user_data])
    user_df = user_df.reindex(columns=feature_columns, fill_value=0)
    
    loan_status = clf.predict(user_df)[0]
    
    if loan_status == 1:
        max_loan_amount = reg_approved.predict(user_df)[0]
        if requested_loan.value <= max_loan_amount:
            print(f"✅ Loan Approved! You are eligible for {requested_loan.value}. Maximum Loan Amount: {max_loan_amount:.2f}")
        else:
            print(f"✅ Loan Approved! But maximum you can get is {max_loan_amount:.2f}. Requested amount is too high.")
    else:
        max_loan_amount = reg_rejected.predict(user_df)[0]
        print(f"❌ Loan Rejected. You requested {requested_loan.value}, but the maximum you might get is {max_loan_amount:.2f}")

# Attach function to button
predict_button.on_click(predict_loan_status)

# Display widgets
display(gender, married, dependents, education, self_employed, applicant_income, 
        coapplicant_income, loan_term, credit_history, property_area, requested_loan, predict_button)


Dropdown(description='Gender:', options=(('Male', 0), ('Female', 1)), value=0)

Dropdown(description='Married:', options=(('No', 0), ('Yes', 1)), value=0)

IntSlider(value=1, description='Dependents:', max=5)

Dropdown(description='Education:', options=(('Graduate', 0), ('Not Graduate', 1)), value=0)

Dropdown(description='Self-Employed:', options=(('No', 0), ('Yes', 1)), value=0)

IntText(value=5000, description='Applicant Income:')

IntText(value=2000, description='Coapplicant Income:')

IntSlider(value=360, description='Loan Term:', max=480, min=12, step=12)

Dropdown(description='Credit History:', options=(('No', 0), ('Yes', 1)), value=0)

Dropdown(description='Property Area:', options=(('Urban', 0), ('Semiurban', 1), ('Rural', 2)), value=0)

IntText(value=100000, description='Requested Loan Amount:')

Button(description='Check Eligibility', style=ButtonStyle())

❌ Loan Rejected. You requested 100000, but the maximum you might get is 150.87


In [2]:
!git init

Reinitialized existing Git repository in C:/Users/pokif/OneDrive/Desktop/Data/Credit predictive model/.git/


In [4]:
!git add .

In [7]:
!git commit -m "new"

[main (root-commit) 6b37212] new
 1 file changed, 2454 insertions(+)
 create mode 100644 Model.ipynb


In [1]:
!git status

On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Model.ipynb

no changes added to commit (use "git add" and/or "git commit -a")
