In [1]:
!pip install ipywidgets

In [2]:
import numpy as np
import pandas as pd
import ipywidgets as widgets
from IPython.display import display
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection  import train_test_split

In [3]:
aj=pd.read_csv(r"D:\30 Cource\CreditRisk.csv")
aj.head(5)

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
aj.drop(['Loan_ID'],axis=1)

Gender Married  Dependents     Education Self_Employed  ApplicantIncome  \
0     Male      No         0.0      Graduate            No             5849   
1     Male     Yes         1.0      Graduate            No             4583   
2     Male     Yes         0.0      Graduate           Yes             3000   
3     Male     Yes         0.0  Not Graduate            No             2583   
4     Male      No         0.0      Graduate            No             6000   
..     ...     ...         ...           ...           ...              ...   
976   Male     Yes         4.0  Not Graduate           Yes             4009   
977   Male     Yes         0.0      Graduate            No             4158   
978   Male      No         0.0      Graduate            No             3250   
979   Male     Yes         0.0      Graduate            No             5000   
980   Male      No         0.0      Graduate           Yes             9200   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
976             1777.0       113.0             360.0             1.0   
977              709.0       115.0             360.0             1.0   
978             1993.0       126.0             360.0             NaN   
979             2393.0       158.0             360.0             1.0   
980                0.0        98.0             180.0             1.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
976         Urban           Y  
977         Urban           Y  
978     Semiurban           Y  
979         Rural           N  
980         Rural           Y  

[981 rows x 12 columns]

In [5]:
aj.isnull().sum()

Loan_ID               0
Gender               24
Married               3
Dependents           25
Education             0
Self_Employed        55
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           27
Loan_Amount_Term     20
Credit_History       79
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
#Null Values
aj.Gender=aj.Gender.fillna("Male")
aj.Married=aj.Married.fillna("Yes")
aj.Dependents=aj.Dependents.fillna(1.0)
aj.Self_Employed=aj.Self_Employed.fillna("No")
aj.LoanAmount=aj.LoanAmount.fillna(aj.LoanAmount.mean())
aj.Loan_Amount_Term=aj.Loan_Amount_Term.fillna(aj.Loan_Amount_Term.mean())
aj.Credit_History=aj.Credit_History.fillna(0)

#Text to numrical
aj.Gender=aj.Gender.replace({'Male':0,'Female':1})
aj.Married=aj.Married.replace({'No':0,'Yes':1})
aj.Education=aj.Education.replace({"Graduate":0,"Not Graduate":1})
aj.Self_Employed=aj.Self_Employed.replace({"No":0,"Yes":1})
aj.Property_Area=aj.Property_Area.replace({"Urban":0,"Semiurban":1,"Rural":2})
aj.Loan_Status=aj.Loan_Status.replace({"Y":1,"N":0})



aj=aj.drop(['Loan_ID'],axis=1)

In [7]:
aj.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [8]:
aj

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         0        0         0.0          0              0             5849   
1         0        1         1.0          0              0             4583   
2         0        1         0.0          0              1             3000   
3         0        1         0.0          1              0             2583   
4         0        0         0.0          0              0             6000   
..      ...      ...         ...        ...            ...              ...   
976       0        1         4.0          1              1             4009   
977       0        1         0.0          0              0             4158   
978       0        0         0.0          0              0             3250   
979       0        1         0.0          0              0             5000   
980       0        0         0.0          0              1             9200   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0   142.51153             360.0             1.0   
1               1508.0   128.00000             360.0             1.0   
2                  0.0    66.00000             360.0             1.0   
3               2358.0   120.00000             360.0             1.0   
4                  0.0   141.00000             360.0             1.0   
..                 ...         ...               ...             ...   
976             1777.0   113.00000             360.0             1.0   
977              709.0   115.00000             360.0             1.0   
978             1993.0   126.00000             360.0             0.0   
979             2393.0   158.00000             360.0             1.0   
980                0.0    98.00000             180.0             1.0   

     Property_Area  Loan_Status  
0                0            1  
1                2            0  
2                0            1  
3                0            1  
4                0            1  
..             ...          ...  
976              0            1  
977              0            1  
978              1            1  
979              2            0  
980              2            1  

[981 rows x 12 columns]

In [9]:
train_aj,test_aj=train_test_split(aj,train_size=0.8,test_size=0.2)
train_aj.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
13        0        0         0.0          0              0             1853   
749       0        1         0.0          0              0             4258   
596       0        1         2.0          1              1             6383   
738       1        0         0.0          0              0            12500   
315       0        1         1.0          1              0             3399   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
13              2840.0       114.0             360.0             1.0   
749                0.0       125.0             360.0             1.0   
596             1000.0       187.0             360.0             1.0   
738                0.0       300.0             360.0             0.0   
315             1640.0       111.0             180.0             1.0   

     Property_Area  Loan_Status  
13               2            0  
749              0            1  
596              2            0  
738              0            0  
315              0            1

In [10]:
x_train=train_aj.iloc[:,0:-1]
y_train=train_aj.iloc[:,-1]

x_test=test_aj.iloc[:,0:-1]
y_test=test_aj.iloc[:,-1]

#1. Scikit-learn Models

In [11]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, accuracy_score, classification_report, confusion_matrix


In [12]:
###                           Linear Regression                           ###

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)
predictions = model.predict(x_test)
predictions

array([0.79961546, 0.86540834, 0.37009294, 0.80023331, 0.8707121 ,
       0.84158014, 0.25621327, 0.77223524, 0.80278096, 0.43073193,
       0.91584657, 0.8940615 , 0.73947469, 0.89547251, 0.87815603,
       0.75348387, 0.81962598, 0.99419692, 0.81978803, 0.93415368,
       0.83344431, 0.3419332 , 0.72509871, 0.91284998, 0.89032246,
       0.95716758, 0.71952227, 0.8421477 , 0.78786718, 0.82331592,
       0.91425745, 0.85859004, 0.72986319, 0.86960484, 0.87195344,
       0.98738561, 0.67749166, 0.3870659 , 0.7113039 , 0.94862034,
       0.23969311, 0.37924772, 0.78310774, 0.37318904, 0.85799264,
       1.11146853, 0.66280347, 0.31373769, 0.33947345, 0.28062312,
       0.72037267, 0.37252538, 0.77270359, 0.84329637, 0.79487299,
       0.91864833, 0.9035759 , 0.78359538, 0.89361329, 0.85394358,
       0.85967222, 0.82053247, 0.35154512, 0.32192232, 0.36616315,
       0.90682397, 0.90213261, 0.95976235, 0.90160386, 0.36174037,
       0.85390082, 0.79019636, 0.41831466, 0.35710208, 0.83159

In [13]:
# Calculate evaluation metrics
r2 = r2_score(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)

print(f'R² Score: {r2}')
print(f'Mean Absolute Error (MAE): {mae}')
print(f'Mean Squared Error (MSE): {mse}')
print(f'Root Mean Squared Error (RMSE): {rmse}')

R² Score: 0.3215399987615545
Mean Absolute Error (MAE): 0.2872378501759252
Mean Squared Error (MSE): 0.13499621555730054
Root Mean Squared Error (RMSE): 0.36741831140717596


In [14]:
###                             Decision Tree                             ###

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train, y_train)
predictions = model.predict(x_test)
predictions

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
      dtype=int64)

In [15]:
# Calculate evaluation metrics
accuracy = accuracy_score(y_test, predictions)
report = classification_report(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions)

# Print results
print(f'Accuracy Score: {accuracy}')
print('Classification Report:\n', report)
print('Confusion Matrix:\n', conf_matrix)

Accuracy Score: 0.7715736040609137
Classification Report:
               precision    recall  f1-score   support

           0       0.58      0.61      0.59        54
           1       0.85      0.83      0.84       143

    accuracy                           0.77       197
   macro avg       0.71      0.72      0.72       197
weighted avg       0.78      0.77      0.77       197

Confusion Matrix:
 [[ 33  21]
 [ 24 119]]


In [16]:
###                         Random Forest                               ###

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train, y_train)
Ran_predictions = model.predict(x_train)
predictions

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
      dtype=int64)

In [17]:
# Predictions on the test set
Ran_predictions = model.predict(x_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, Ran_predictions)
report = classification_report(y_test, Ran_predictions)
conf_matrix = confusion_matrix(y_test, Ran_predictions)

# Print results
print(f'Accuracy Score: {accuracy}')
print('Classification Report:\n', report)
print('Confusion Matrix:\n', conf_matrix)

Accuracy Score: 0.8223350253807107
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.63      0.66        54
           1       0.86      0.90      0.88       143

    accuracy                           0.82       197
   macro avg       0.78      0.76      0.77       197
weighted avg       0.82      0.82      0.82       197

Confusion Matrix:
 [[ 34  20]
 [ 15 128]]


In [18]:
# Splitting dataset into train-test
train_aj, test_aj = train_test_split(aj, train_size=0.8, test_size=0.2, random_state=42)

In [19]:
# Define feature columns
feature_columns = [col for col in aj.columns if col not in ['Loan_Status', 'LoanAmount']]

In [20]:
# Features & target for classification
X_train = train_aj[feature_columns]
y_train = train_aj['Loan_Status']

X_test = test_aj[feature_columns]
y_test = test_aj['Loan_Status']

In [21]:
# Train Random Forest Classifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [22]:
# Classification Accuracy
y_pred = clf.predict(X_test)
print("Loan Approval Accuracy:", accuracy_score(y_test, y_pred))


Loan Approval Accuracy: 0.766497461928934


In [23]:
# Train Regression Models for Loan Amount Prediction
approved_loans = train_aj[train_aj['Loan_Status'] == 1]
rejected_loans = train_aj[train_aj['Loan_Status'] == 0]

reg_approved = RandomForestRegressor(random_state=42)
reg_rejected = RandomForestRegressor(random_state=42)

reg_approved.fit(approved_loans[feature_columns], approved_loans['LoanAmount'])
reg_rejected.fit(rejected_loans[feature_columns], rejected_loans['LoanAmount'])

RandomForestRegressor(random_state=42)

In [24]:
# Define interactive widgets
gender = widgets.Dropdown(options=[("Male", 0), ("Female", 1)], description="Gender:")
married = widgets.Dropdown(options=[("No", 0), ("Yes", 1)], description="Married:")
dependents = widgets.IntSlider(min=0, max=5, value=1, description="Dependents:")
education = widgets.Dropdown(options=[("Graduate", 0), ("Not Graduate", 1)], description="Education:")
self_employed = widgets.Dropdown(options=[("No", 0), ("Yes", 1)], description="Self-Employed:")
applicant_income = widgets.IntText(value=5000, description="Applicant Income:")
coapplicant_income = widgets.IntText(value=2000, description="Coapplicant Income:")
loan_term = widgets.IntSlider(min=12, max=480, value=360, step=12, description="Loan Term:")
credit_history = widgets.Dropdown(options=[("No", 0), ("Yes", 1)], description="Credit History:")
property_area = widgets.Dropdown(options=[("Urban", 0), ("Semiurban", 1), ("Rural", 2)], description="Property Area:")
requested_loan = widgets.IntText(value=100000, description="Requested Loan Amount:")
predict_button = widgets.Button(description="Check Eligibility")
# Function to predict loan status
def predict_loan_status(_):
    user_data = {
        "Gender": gender.value,
        "Married": married.value,
        "Dependents": dependents.value,
        "Education": education.value,
        "Self_Employed": self_employed.value,
        "ApplicantIncome": applicant_income.value,
        "CoapplicantIncome": coapplicant_income.value,
        "Loan_Amount_Term": loan_term.value,
        "Credit_History": credit_history.value,
        "Property_Area": property_area.value,
    }
    
    user_df = pd.DataFrame([user_data])
    user_df = user_df.reindex(columns=feature_columns, fill_value=0)
    
    loan_status = clf.predict(user_df)[0]
    
    if loan_status == 1:
        max_loan_amount = reg_approved.predict(user_df)[0]
        if requested_loan.value <= max_loan_amount:
            print(f"✅ Loan Approved! You are eligible for {requested_loan.value}. Maximum Loan Amount: {max_loan_amount:.2f}")
        else:
            print(f"✅ Loan Approved! But maximum you can get is {max_loan_amount:.2f}. Requested amount is too high.")
    else:
        max_loan_amount = reg_rejected.predict(user_df)[0]
        print(f"❌ Loan Rejected. You requested {requested_loan.value}, but the maximum you might get is {max_loan_amount:.2f}")

# Attach function to button
predict_button.on_click(predict_loan_status)

# Display widgets
display(gender, married, dependents, education, self_employed, applicant_income, 
        coapplicant_income, loan_term, credit_history, property_area, requested_loan, predict_button)


Dropdown(description='Gender:', options=(('Male', 0), ('Female', 1)), value=0)

Dropdown(description='Married:', options=(('No', 0), ('Yes', 1)), value=0)

IntSlider(value=1, description='Dependents:', max=5)

Dropdown(description='Education:', options=(('Graduate', 0), ('Not Graduate', 1)), value=0)

Dropdown(description='Self-Employed:', options=(('No', 0), ('Yes', 1)), value=0)

IntText(value=5000, description='Applicant Income:')

IntText(value=2000, description='Coapplicant Income:')

IntSlider(value=360, description='Loan Term:', max=480, min=12, step=12)

Dropdown(description='Credit History:', options=(('No', 0), ('Yes', 1)), value=0)

Dropdown(description='Property Area:', options=(('Urban', 0), ('Semiurban', 1), ('Rural', 2)), value=0)

IntText(value=100000, description='Requested Loan Amount:')

Button(description='Check Eligibility', style=ButtonStyle())

In [27]:
!git init

Reinitialized existing Git repository in C:/Users/pokif/OneDrive/Desktop/Data/Credit-predictive-model/.git/


In [39]:
!git add Model.ipynb

In [41]:
!git commit -m "Model change"

[main 4cc4063] Model change
 1 file changed, 6 insertions(+), 6 deletions(-)


In [42]:
!git status

On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Model.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [32]:
!git remote add origin https://github.com/Creativity-studio-101/Credit_pridiction.git

error: remote origin already exists.


In [26]:
!git remote -v

origin	https://github.com/Creativity-studio-101/Credit_pridiction.git (fetch)
origin	https://github.com/Creativity-studio-101/Credit_pridiction.git (push)


In [33]:
!git branch

* main


In [34]:
!git push origin main

fatal: unable to access 'https://github.com/Creativity-studio-101/Credit_pridiction.git/': Could not resolve host: github.com
